Blocked radius for warzone
Muqsit/Wilderness pull request #5
Opened 2020-05-21 21:00 UTC by Unickorn

This pull request adds support for a configurable blocked center area that can be used for blocking a warzone players are not meant to /wild into.

2020-05-21 21:08 UTC, Muqsit commented
Can you please be more informative about it? I'm not sure how adding/subtracting a value from min/max can be beneficial.

2020-05-21 21:12 UTC, Muqsit requested changes

2020-05-21 21:12 UTC, Muqsit commented on src/muqsit/wilderness/math/ClosedInterval.php
> +	public function __construct(int $min, int $max, int $center, int $radius){
Do you understand what a closed interval is in mathematics? It literally makes no sense for a closed interval to be having a center and radius properties. 🤔 
https://en.wikipedia.org/wiki/Interval_(mathematics)#Terminology

2020-05-21 22:11 UTC, Unickorn commented on src/muqsit/wilderness/math/ClosedInterval.php
> +	public function __construct(int $min, int $max, int $center, int $radius){
Would moving the center and blocked "radius" (not even sure what to call it) values o the Random2DCoordinateGenerator make more sense? I'm not sure how to go with this.

I mainly wanted to block an inner x by x area from the /wild and reserve it as a warzone people can't /wild into.

2020-05-22 00:00 UTC, Muqsit commented on src/muqsit/wilderness/math/ClosedInterval.php
> +	public function __construct(int $min, int $max, int $center, int $radius){
Random2DCoordinateGenerator serves it's use of generating a random 2D point, it need not do anything more than what's it named for.

A better approach would be to abstract the generation code so other plugins can interfere.
Blocking specific regions isn't something Wilderness should be equipped with. It must be something a region managing plugin should inject — not all regions are rectangular.

2020-05-23 08:33 UTC, closed without merging